'use client';

import { useState } from 'react';
import { useAuthStore } from '@/store/useStore';
import { useRouter } from 'next/navigation';
import Navbar from '@/components/Navbar';
import { GoogleGenAI, Type } from '@google/genai';
import { collection, addDoc, serverTimestamp, writeBatch, doc } from 'firebase/firestore';
import { db } from '@/lib/firebase';

export default function AICreator() {
  const [topic, setTopic] = useState('');
  const [count, setCount] = useState(5);
  const [loading, setLoading] = useState(false);
  const [generatedCards, setGeneratedCards] = useState<any[]>([]);
  const [deckTitle, setDeckTitle] = useState('');
  const { user } = useAuthStore();
  const router = useRouter();

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!user) return;
    
    setLoading(true);
    setGeneratedCards([]);

    try {
      const ai = new GoogleGenAI({ apiKey: process.env.NEXT_PUBLIC_GEMINI_API_KEY });
      
      const prompt = `Generate ${count} high-quality flashcards based on the following topic or text: ${topic}.
      The flashcards should be concise, clear, and focus on key concepts.
      Return the result as a JSON array of objects, where each object has a 'front' (the question or concept) and a 'back' (the answer or explanation).`;

      const response = await ai.models.generateContent({
        model: 'gemini-3-flash-preview',
        contents: prompt,
        config: {
          responseMimeType: 'application/json',
          responseSchema: {
            type: Type.ARRAY,
            items: {
              type: Type.OBJECT,
              properties: {
                front: {
                  type: Type.STRING,
                  description: 'The front of the flashcard (question or concept)',
                },
                back: {
                  type: Type.STRING,
                  description: 'The back of the flashcard (answer or explanation)',
                },
              },
              required: ['front', 'back'],
            },
          },
        },
      });

      const jsonStr = response.text?.trim() || '[]';
      const cards = JSON.parse(jsonStr);
      
      setGeneratedCards(cards);
      setDeckTitle(`AI Generated: ${topic.substring(0, 30)}${topic.length > 30 ? '...' : ''}`);
    } catch (error) {
      console.error('Error generating cards', error);
      alert('Failed to generate cards. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleSaveDeck = async () => {
    if (!deckTitle || generatedCards.length === 0 || !user) return;
    setLoading(true);

    try {
      // 1. Create Deck
      const deckRef = await addDoc(collection(db, 'decks'), {
        title: deckTitle,
        description: `Generated by FlashMind AI for topic: ${topic}`,
        tags: ['ai-generated', topic.split(' ')[0].toLowerCase()],
        userId: user.id,
        isPublic: false,
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp(),
      });

      // 2. Create Cards in a batch
      const batch = writeBatch(db);
      for (const card of generatedCards) {
        const cardRef = doc(collection(db, 'cards'));
        batch.set(cardRef, {
          deckId: deckRef.id,
          userId: user.id,
          front: card.front,
          back: card.back,
          tags: card.tags || [],
          repetitions: 0,
          easeFactor: 2.5,
          interval: 0,
          nextReviewDate: serverTimestamp(),
          createdAt: serverTimestamp(),
          updatedAt: serverTimestamp(),
        });
      }
      await batch.commit();

      router.push(`/decks/${deckRef.id}`);
    } catch (error) {
      console.error('Failed to save deck', error);
      alert('Failed to save deck. Please try again.');
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-surface">
      <Navbar />
      <main className="pt-24 pb-32 px-6 max-w-5xl mx-auto">
        <div className="text-center mb-12">
          <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-primary/10 text-primary text-3xl mb-6">✨</div>
          <h1 className="text-4xl md:text-5xl font-bold font-headline tracking-tighter text-on-surface mb-4">AI Flashcard Creator</h1>
          <p className="text-on-surface-variant max-w-2xl mx-auto">Transform any topic or text into a comprehensive study deck in seconds using the power of Gemini AI.</p>
        </div>

        {!generatedCards.length ? (
          <form onSubmit={handleGenerate} className="max-w-2xl mx-auto bg-surface-container p-8 rounded-2xl border border-outline-variant/10 shadow-2xl">
            <div className="space-y-6">
              <div>
                <label className="block text-xs font-bold tracking-widest uppercase text-on-surface-variant mb-2">Topic or Text</label>
                <textarea
                  value={topic}
                  onChange={(e) => setTopic(e.target.value)}
                  className="w-full bg-surface-container-low border-none border-b border-outline-variant/30 focus:border-primary focus:ring-0 rounded-xl px-4 py-4 text-on-surface min-h-[150px] resize-y"
                  placeholder="Paste your notes, or enter a topic like 'Photosynthesis' or 'French Revolution'..."
                  required
                />
              </div>

              <div>
                <label className="block text-xs font-bold tracking-widest uppercase text-on-surface-variant mb-2">Number of Cards</label>
                <div className="flex items-center gap-4">
                  <input
                    type="range"
                    min="5"
                    max="20"
                    value={count}
                    onChange={(e) => setCount(parseInt(e.target.value))}
                    className="flex-1 accent-primary"
                  />
                  <span className="text-xl font-bold text-primary w-12 text-center">{count}</span>
                </div>
              </div>

              <button 
                type="submit" 
                disabled={loading || !topic}
                className="w-full bg-primary text-on-primary py-4 rounded-xl font-bold text-sm tracking-tight active:scale-95 transition-transform disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
              >
                {loading ? (
                  <>
                    <span className="animate-spin text-xl">↻</span>
                    Generating Magic...
                  </>
                ) : (
                  <>Generate Flashcards</>
                )}
              </button>
            </div>
          </form>
        ) : (
          <div className="space-y-8 animate-in fade-in slide-in-from-bottom-8 duration-500">
            <div className="flex flex-col md:flex-row justify-between items-start md:items-end gap-4 bg-surface-container p-6 rounded-2xl border border-primary/20">
              <div className="flex-1 w-full">
                <label className="block text-xs font-bold tracking-widest uppercase text-primary mb-2">Deck Title</label>
                <input
                  type="text"
                  value={deckTitle}
                  onChange={(e) => setDeckTitle(e.target.value)}
                  className="w-full bg-transparent border-none border-b border-primary/30 focus:border-primary focus:ring-0 px-0 py-2 text-2xl font-bold font-headline text-on-surface"
                />
              </div>
              <div className="flex gap-4 w-full md:w-auto">
                <button onClick={() => setGeneratedCards([])} className="flex-1 md:flex-none px-6 py-3 rounded-xl font-bold text-sm text-on-surface-variant hover:bg-surface-container-highest transition-colors">
                  Discard
                </button>
                <button 
                  onClick={handleSaveDeck}
                  disabled={loading}
                  className="flex-1 md:flex-none bg-primary text-on-primary px-8 py-3 rounded-xl font-bold text-sm tracking-tight active:scale-95 transition-transform shadow-[0_0_20px_rgba(184,196,255,0.3)]"
                >
                  {loading ? 'Saving...' : 'Save Deck to Library'}
                </button>
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {generatedCards.map((card, idx) => (
                <div key={idx} className="bg-surface-container p-6 rounded-xl border border-outline-variant/10 flex flex-col gap-4">
                  <div>
                    <span className="text-[10px] font-bold tracking-widest uppercase text-primary/70 mb-1 block">Front</span>
                    <p className="text-lg font-bold text-on-surface">{card.front}</p>
                  </div>
                  <div className="w-full h-px bg-outline-variant/10"></div>
                  <div>
                    <span className="text-[10px] font-bold tracking-widest uppercase text-on-surface-variant/70 mb-1 block">Back</span>
                    <p className="text-on-surface-variant">{card.back}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
